[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "labquiz"
version = "0.9.5"
description = "LabQuiz is a Python package that allows to integrate interactive quizzes directly into Jupyter notebooks — useful for labs, tutorials, practical assignments, continuous assessment, and controlled exams"
readme = "README.md"
license = { text = "GPL-3.0-or-later" }
authors = [
    { name = "J.-F. Bercher", email = "jf.bercher@esiee.fr" }
]
dependencies = [
    "ipywidgets>=7.6.5",
    "pyyaml",
    "cryptography",
    "ipython",
    "numpy",
    "pandas",
    "requests",
]
keywords = ["quizzes", "jupyter", "hash:840c7701c82787f943366de56a9ec7210fceb91f013390d83e6e9129781dfe18"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"labquiz" = ["**/*.mo", "**/*.po"]

[project.optional-dependencies]
demo = [
  "jupyterlab_myst",
]