[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "labquiz"
version = "0.9.10"
description = "LabQuiz is a Python package that allows to integrate interactive quizzes directly into Jupyter notebooks — useful for labs, tutorials, practical assignments, continuous assessment, and controlled exams"
readme = "README.md"
license = "GPL-3.0-or-later"

authors = [
    { name = "J.-F. Bercher", email = "jf.bercher@esiee.fr" }
]
dependencies = [
    "ipywidgets>=7.6.5",
    "pyyaml",
    "cryptography",
    "ipython",
    "numpy",
    "pandas",
    "requests",
]
keywords = ["quizzes", "jupyter", "hash:e2fc9cc264ed5c547436f2eacabdfd844ac04295b8dc1ac5bb9cc99cff385e2a"]

classifiers = [
    # État de développement (3 - Alpha, 4 - Beta, 5 - Production/Stable)
    "Development Status :: 4 - Beta",
    
    # Public cible
    "Intended Audience :: Education",


    # VERSIONS PYTHON : Très important pour le badge "Python versions"
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    
    # Environnement
    "Topic :: Education",
    "Topic :: Software Development :: User Interfaces",
]

[project.urls]
"Homepage" = "https://github.com/jfbercher/labquiz"
"Bug Tracker" = "https://github.com/jfbercher/labquiz/issues"
"Documentation" = "https://labquiz.readthedocs.io/en/latest/"
"Source" = "https://github.com/jfbercher/labquiz"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"labquiz" = ["**/*.mo", "**/*.po"]

[project.optional-dependencies]
demo = [
  "jupyterlab_myst",
]