[project]
name = "LabQuizBundle"
version = "1.0.0"
description = "LabQuiz bundle that includes labquiz, quiz-editor, and quiz-dash."
readme = "README.md"
license = "GPL-3.0-or-later"
authors = [
    { name = "J.-F. Bercher", email = "jf.bercher@esiee.fr" }
]

dependencies = [
    "labquiz==1.0.0",
    "quiz_editor==1.0.0",
    "quiz_dash==1.0.0"
]

keywords = ["quizzes", "jupyter"]

classifiers = [
    # État de développement (3 - Alpha, 4 - Beta, 5 - Production/Stable)
    "Development Status :: 4 - Beta",
    
    # Public cible
    "Intended Audience :: Education",
    "Intended Audience :: Developers",


    # VERSIONS PYTHON : Très important pour le badge "Python versions"
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    
    # Environnement
    "Operating System :: OS Independent",
    "Topic :: Education",
    "Topic :: Software Development :: User Interfaces",
]

[project.urls]
"Homepage" = "https://github.com/jfbercher/labquiz"
"Bug Tracker" = "https://github.com/jfbercher/labquiz/issues"
"Documentation" = "https://labquiz.readthedocs.io/en/latest/"
"Source" = "https://github.com/jfbercher/labquiz"